<?php

namespace MWSimple\Bundle\ForoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseEntradaRepository extends EntityRepository
{
}
