<?php

namespace MWSimple\Bundle\ForoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaRepository extends EntityRepository {

	public function getEntradasForo($foroId)
    {
        $qb = $this->createQueryBuilder('entrada')
                   ->select('entrada')
                   ->where('entrada.grupo = :entrada_id')
                   //->addOrderBy('entrada.created')
                   ->setParameter('entrada_id', $foroId);

        return $qb->getQuery()
                  ->getResult();
    }

}
